version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "./init-venv.sh && source .venv/bin/activate && ./build-single-file.sh"
    working_dir: /workdir
    volumes:
      - ./:/workdir
      - hostup-dns-client-venv:/workdir/.venv

volumes:
  hostup-dns-client-venv:
