name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    runs-on: python:3-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          apk add binutils
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest -v *_test.py
        working-directory: src

      - name: Build executable with PyInstaller
        run: |

          # Extract version from src/version.py
          version=$(grep "__version__" src/version.py | sed -E 's/__version__ = "(.*)"/\1/')

          echo "Version found: $version"

          pyinstaller --onefile --name hostup-dns-client-${version} src/main.py
          time ./dist/hostup-dns-client-${version} --help

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/hostup-dns-client-*
