name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Run unit tests
        run: |
          python -m unittest *_test.py
        working-directory: src

      # Create executable with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile src/main.py
          time ./dist/main --help
